addSbtPlugin("org.scalameta"      % "sbt-scalafmt"        % "2.5.2")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"             % "0.4.7")
addSbtPlugin("com.typesafe.sbt"   % "sbt-native-packager" % "1.3.4")
addSbtPlugin("com.eed3si9n"       % "sbt-assembly"        % "0.14.10")
addSbtPlugin("com.github.sbt" % "sbt-ci-release" % "<version>")
